FROM python:3-slim

RUN useradd --create-home --shell /bin/bash cyverse
USER cyverse
WORKDIR /home/cyverse

RUN set -x \
    && pip install genshi

COPY metadata_client.py meta2tbl.py ./

VOLUME [ "/home/cyverse/config" ]

ENTRYPOINT [ "python", "/home/cyverse/meta2tbl.py" ]
CMD [ "--help" ]
