FROM python:3-slim

WORKDIR /root

RUN mkdir config templates schemas
COPY config config/
COPY templates templates/
COPY schemas schemas/

VOLUME [ "/root/config", "/root/templates", "/root/schemas" ]
